# separate automation file
#       
#- alias: 'Shutdown pi via command line on remote'
#  trigger:
#    platform: event
#    event_type: ir_command_received
#    event_data:
#      button_name: key_power
#  action:
#    service: shell_command.shutdown_pi
- alias: 'Set a scene with the philips hue bulbs when we watch tv with the harmony'
  hide_entity: False
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_nine
  action:
    - service: light.hue_activate_scene
      data:
        group_name: "Bedroom"
        scene_name: "Bedroom Warm"
        
 #following state machine for TV on-off
 
- alias: 'Following state machine for TV'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: lg_tv_power
  action:
    - service: homeassistant.toggle
      entity_id: input_boolean.lg_tv_status

- alias: 'Following state machine for Apple TV'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: apple_tv_playpause
  action:
    - service: homeassistant.turnon
      entity_id: input_boolean.apple_tv_status

- alias: 'Following state machine for Teac Amplifier'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: teac_power
  action:
    - service: homeassistant.toggle
      entity_id: input_boolean.teac_amp_status

#- alias: 'Following state machine for TV -off'
#  trigger:
#    platform: event
#    event_type: ir_command_received
#    event_data:
#      button_name: key_playpause
#  action:
#    - service: homeassistant.turn_off
#      entity_id: input_boolean.lg_tv_status

- alias: 'Text Alex about power down'
  hide_entity: False
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_power
  action:
    - service: notify.sms_notify
      data:
        message: 'Someone pressed the power key'
        target:
          - !secret twilio_to_number

#Nest motion detection
- alias: 'Nobody Home'
  trigger:
    platform: state
    entity_id: sensor.bedroom_away_mode, sensor.den_away_mode
    to: 'False'
  condition:
    condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
    service: notify.sms_notify
    data:
      message: 'In your base, stealing your mans'
      target:
        - !secret twilio_to_number

#Return lights to preset color temp when Night Shift goes off
- alias: 'Night Shift Off -Den'
  trigger:
    platform: state
    entity_id: switch.night_shift
    to: 'off'
  condition:
    condition: state
    entity_id: light.den
    state: 'on'
  action:
    service: light.hue_activate_scene
    data:
      group_name: "Den"
      scene_name: "Den Mid Warm"
      
- alias: 'Night Shift Off -Bedroom'
  trigger:
    platform: state
    entity_id: switch.night_shift
    to: 'off'
  condition:
    condition: state
    entity_id: light.bedroom
    state: 'on'
  action:
    service: light.hue_activate_scene
    data:
      group_name: "Bedroom"
      scene_name: "Bedroom Night"

- alias: 'Night Shift Off -Kitchen'
  trigger:
    platform: state
    entity_id: switch.night_shift
    to: 'off'
  condition:
    condition: state
    entity_id: light.kitchen
    state: 'on'
  action:
    service: light.hue_activate_scene
    data:
      group_name: "Kitchen"
      scene_name: "Kitchen Full Bright"
      
#turning the flux switch off for each light
- alias: 'Night shift on den'
  trigger:
    platform: state
    entity_id: light.den
    to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.night_shift_den

#reverse back on when engaged
- alias: 'Night shift off den'
  trigger:
    platform: state
    entity_id: light.den
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.night_shift
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.night_shift_den
      
#night shift for the kitchen       
- alias: 'Night shift off kitchen'
  trigger:
    platform: state
    entity_id: light.kitchen
    to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.night_shift_kitchen

#reverse back on when engaged
- alias: 'Night shift on kitchen'
  trigger:
    platform: state
    entity_id: light.kitchen
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.night_shift
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.night_shift_kitchen

#bedroom lights flux
- alias: 'Night shift off bedroom'
  trigger:
    platform: state
    entity_id: light.bedroom
    to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.night_shift_bedroom

#reverse back on when engaged
- alias: 'Night shift on bedroom'
  trigger:
    platform: state
    entity_id: light.bedroom
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.night_shift
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.night_shift_bedroom

#set the nests to away and the lights to off 30 minutes after bluetooth disconnects
- alias: 'Away on iPhone'
  trigger:
    platform: state
    entity_id: device_tracker.alexs_iphone
    to: 'away'
  action:
    - delay: '00:00:30'
    - service: light.turn_off
    - service: switch.turn_off
      entity_id: switch.table_light
    - service: climate.set_hold_mode
      data:
        entity_id: climate.den
        hold_mode: 'away'

- alias: 'Home on iPhone'
  trigger:
    platform: state
    entity_id: device_tracker.alexs_iphone
    to: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.table_light
    - service: climate.set_hold_mode
      data:
        entity_id: climate.den
        hold_mode: 'home'

#- alias: 'OpenVPN Working'
#  trigger:
#    platform: state
#    entity_id: sensor.openvpn
##    to: 'False'
 #  action:
 #    service: notify.sms_notify
 #    data:
  #   message: 'OpenVPN Down!'
  #   target:
  #     - !secret twilio_to_number
       
- alias: 'OpenVPN Down'
  trigger:
    platform: state
    entity_id: sensor.openvpn
    to: 'False'
  action:
    service: notify.sms_notify
    data:
      message: 'OpenVPN is down!'
      target:
        - +12022361848   
        
#fireTV mapping for infrared to web control
- alias: 'transmit power on command fire TV'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: fire_tv_power
  action:
    - service: media_player.turn_on
      entity_id: media_player.fire_tv
      
- alias: 'transmit play command fire TV'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: fire_tv_play
  action:
    - service: media_player.play
      entity_id: media_player.fire_tv
 
 - alias: 'transmit pause command fire TV'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: fire_tv_pause
  action:
    - service: media_player.pause
      entity_id: media_player.fire_tv
