# separate automation file
#- alias: 'Power Cycle on Remote'
#  trigger:
#    platform: event
#    event_type: ir_command_received
#    event_data:
#      button_name: key_playpause
#  action:
#   - service: notify.pushbullet
#     data:
#       message: "received IR command"
#       title: "received IR command"
#       
- alias: 'Shutdown pi via command line on remote'
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_power
  action:
    service: shell_command.shutdown_pi
    
- alias: 'Set a scene with the philips hue bulbs when we watch tv with the harmony'
  hidden: true
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_nine
  action:
    - service: light.hue_activate_scene
      data:
        group_name: "Bedroom"
        scene_name: "Bedroom Warm"
        
- alias: 'Following state machine for TV'
  #hidden: true
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_power
    action:
      - state: LG TV|state
        data: off
        
