# separate automation file
#       
#- alias: 'Shutdown pi via command line on remote'
#  trigger:
#    platform: event
#    event_type: ir_command_received
#    event_data:
#      button_name: key_power
#  action:
#    service: shell_command.shutdown_pi

- alias: 'Set a scene with the philips hue bulbs when we watch tv with the harmony'
  hide_entity: False
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_nine
  action:
    - service: light.hue_activate_scene
      data:
        group_name: "Bedroom"
        scene_name: "Bedroom Warm"
        
 #following state machine for TV on-off
 
- alias: 'Following state machine for TV'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_playpause
  action:
    - service: homeassistant.toggle
      entity_id: input_boolean.lg_tv_status

- alias: 'Following state machine for Apple TV'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_playpause
  action:
    - service: homeassistant.toggle
      entity_id: input_boolean.apple_tv_status

- alias: 'Following state machine for Teac Amplifier'
  hide_entity: True
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_playpause
  action:
    - service: homeassistant.toggle
      entity_id: input_boolean.teac_amp_status

#- alias: 'Following state machine for TV -off'
#  trigger:
#    platform: event
#    event_type: ir_command_received
#    event_data:
#      button_name: key_playpause
#  action:
#    - service: homeassistant.turn_off
#      entity_id: input_boolean.lg_tv_status

- alias: 'Text Alex about power down'
  hide_entity: False
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: key_power
  action:
    - service: notify.sms_notify
      data:
        message: 'Someone pressed the power key'
        target:
          - +12022361848

#nest away toggle test
- alias: 'Nest Away toggle on'
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_boolean.nest_away_switch
    state: 'on'
  action:
    service: climate.set_away_mode
    entity_id: climate.bedroom
    data:
      away_mode: 'true'

- alias: 'Nest Away toggle off'
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_boolean.nest_away_switch
    state: 'off'
  action:
    service: climate.set_away_mode
    entity_id: climate.bedroom
    event_data:
      away_mode: 'false'  
#Nest motion detection
#- alias: 'Nobody Home'
#  trigger:
#    platform: state
#    entity_id: climate.bedroom_away_mode
#    state: 'off'
#  action:
#    service: notify.sms_notify
#    data:
#      message: 'In your base, stealing your mans'
#      target:
#        - +12022361848
