homeassistant:
  # Name of the location where Home Assistant is running
  name: 632 Mass Ave
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lattitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  #include the customize file
  customize: !include customize.yaml 

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secrets api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google
  
#call LIRC
lirc:

#Call IFTTT
ifttt:
  key: !secret ifttt_key

#Call Nest
nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_secret

#call climate
climate:
  platform: nest

#Call Emulated Hue
emulated_hue:
#  host_ip: 192.168.1.111
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - media_player

#Add notify components
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_apikey

#add shell commands
shell_command:
  shutdown_pi: 'sudo shutdown'

#add switches
switch:
- platform: command_line
  switches:
    tv_ir:
      command_on: "irsend send_once testremote key_power && sudo wall irsend power key"
      command_off: "irsend send_once testremote key_power && sudo wall irsend power key"
      friendly_name: Living Room TV 

- platform: command_line
  switches:
    kitchen_light:
      command_on: "test1"
      command_off: "test2"
      friendly_name: Kitchen Light Switch

#Media players
media_player:
  - platform: universal
    name: LG_TV
    commands:
      turn_on: "irsend send_once testremote key_power && sudo wall irsend power key"
      turn_off: "irsend send_once testremote key_power && sudo wall irsend power key"
      volume_up: "irsend send_once testremote key_volumeup && sudo wall irsend power key"
      volume_down: "irsend send_once testremote key_volumedown && sudo wall irsend power key"
      volume_mute: "irsend send_once testremote key_volumedown && sudo wall irsend power key"
    
    attributes:
      state: switch.tv_ir
      is_volume_muted: switch.tv_ir_mute
    
# source separate automations file
automation: !include automation.yaml   
