homeassistant:
  # Name of the location where Home Assistant is running
  name: 632 Mass Ave
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lattitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  #include the customize file
  customize: !include customize.yaml 


# Show links to resources in log and frontend
#introduction:


# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secrets api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.sun

# Track the sun
sun:

# Weather Prediction
sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google
  
#call LIRC
lirc:

#Call IFTTT
ifttt:
  key: !secret ifttt_key

#Call Nest
nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_secret

#call climate
climate:
  platform: nest

#Call Emulated Hue
emulated_hue:
  #host_ip: 192.168.0.89
  #listen_port: 8300
  #expose_by_default: true
  #exposed_domains:
  #  - light
  #  - switch
  #  - media_player

#Add notify components
notify: !include notifiers.yaml

#add shell commands
shell_command: !include command_lines.yaml

#add device trackers
device_tracker: !include device_tracker.yaml

#add switches
switch: !include switches.yaml

#main hue hub (since netdisco seems to be unhappy)
light:
  platform: hue
  host: 192.168.0.94

#add input booleans
input_boolean: !include input_booleans.yaml

#add scripts
script: !include scripts.yaml

#add binary sensors
binary_sensor: !include binary_sensors.yaml

#add media players
media_player: !include media_players.yaml
  
# source separate automations file
automation: !include automation.yaml   

#call groups separately
group: !include groups.yaml

#call twilio
twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_auth
  #from_number: !secret twilio_from_number
  
#add config for v.39
config:
