homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 38.9413
  longitude: -76.4915
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google
  
#call LIRC
lirc:

#Call IFTTT
ifttt:
  key: cOCvfiDE-V_Svs73mauFDF

#Call Nest
nest:
  client_id: 741449c2-df35-4c3f-9d85-064d0ec276d6
  client_secret: m54H1Rr9gO8YdNI7H7YaN9hj1
  
# source separate automations file
automation: !include automation.yaml

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: o.72dwTslKwhumfsc2tX0IvKetJFtjzelC

#binary_sensor:
#  - platform: nest
#    monitored_conditionn:
