#List of media players
- platform: universal
  name: LG TV
  commands:
    turn_on: 
      service: script.lg_tv_on
    turn_off: 
      service: script.lg_tv_off
    #volume_up: "irsend send_once testremote key_volumeup && sudo wall irsend power key"
    #volume_down: "irsend send_once testremote key_volumedown && sudo wall irsend power key"
    #volume_mute: "irsend send_once testremote key_volumedown && sudo wall irsend power key"
  attributes:
    state: input_boolean.lg_tv_status
      
#- platform: universal
#  name: Apple TV
#  commands:
#    turn_on: 
##      service: script.apple_tv_on
#    turn_off: 
#      service: script.apple_tv_off
#      #volume_up: "irsend send_once testremote key_volumeup && sudo wall apple tv on"
##      #volume_down: "irsend send_once testremote key_volumedown && sudo wall apple tv down"
#      #volume_mute: "irsend send_once testremote key_volumedown && sudo wall irsend power key"
#  attributes:
#    state: sensor.apple_tv_power

- platform: apple_tv
  host: 192.168.0.98
  login_id: !secret  atv_login
  name: Living Room Apple TV
  #start_off: true
  
- platform: universal
  name: Teac Amplifier
  commands:
    turn_on: 
      service: script.teac_amp_on
    turn_off: 
      service: script.teac_amp_off
      #volume_up: "irsend send_once testremote key_volumeup && sudo wall apple tv on"
      #volume_down: "irsend send_once testremote key_volumedown && sudo wall apple tv down"
      #volume_mute: "irsend send_once testremote key_volumedown && sudo wall irsend power key"
  attributes:
    state: binary_sensor.is_teac_amp_online
