#notifier routines
- platform: kodi
  name: rasplex
  host: rasplex_host
  port: 8080

- platform: kodi
  name: rasplex2
  host: rasplex_host2
  port: 8081
  
- platform: pushbullet
  api_key: o.eduhIngOGpW8sNqeTzZZOSfT3ou48b2U
