#sensors to include

#weather platform
- platform: yr

#nest bedroom
- platform: template
  sensors:
     bedroom_away_mode:
       entity_id: climate.bedroom
       value_template: "{{ is_state_attr('climate.upstairs', 'away_mode', 'on') }}"
