#sensors to include

#weather platform
- platform: yr

#nest bedroom
- platform: template
  sensors:
     bedroom_away_mode:
       entity_id: climate.bedroom
       value_template: "{{ is_state_attr('climate.bedroom', 'away_mode', 'on') }}"
       
#nest den       
- platform: template
  sensors:
     den_away_mode:
       entity_id: climate.den
       value_template: "{{ is_state_attr('climate.den', 'away_mode', 'on') }}"

#apple tv bluetooth
- platform: template
  sensors:
    apple_tv_power:
      entity_id: device_tracker.living_room_apple_tv
      value_template: "{% if is_state('device_tracker.living_room_apple_tv', 'home') %}on{% else %}off{% endif %}"

#speed test. To annoy comcast
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
