#File contains switches
  
# den table light
- platform: tplink
  host: 192.168.0.91
  name: Table Light

#flux for den
- platform: flux
  lights:
    - light.den
  name: Night Shift den
  start_time: '7:00'
  stop_time:  '23:00'
  start_colortemp: 7500
  sunset_colortemp: 5000
  stop_colortemp: 3500
  brightness: 255
  mode: mired
  interval: 10
  
#kitchen flux setting
- platform: flux
  lights:
    - light.kitchen
  name: Night Shift Kitchen
  start_time: '7:00'
  stop_time:  '23:00'
  start_colortemp: 7500
  sunset_colortemp: 5000
  stop_colortemp: 3500
  brightness: 255
  mode: xy

#bedroom flux setting
- platform: flux
  lights:
    - light.bedroom
  name: Night Shift bedroom
  start_time: '7:00'
  stop_time:  '23:00'
  start_colortemp: 7500
  sunset_colortemp: 5000
  stop_colortemp: 3500
  brightness: 255
  mode: xy
