#File contains switches
- platform: tplink
  host: 192.168.0.91
  name: Table Light

#adding flux
- platform: flux
  lights:
    - light.den
    - light.kitchen
    - light.bedroom
  name: Night Shift
  start_time: '7:00'
  stop_time:  '23:00'
  start_colortemp: 7500
  sunset_colortemp: 5000
  stop_colortemp: 3500
  brightness: 200
  mode: xy
